name: coolcoffeebot
description: Monetize your Telegram bot with Telegram Stars using Dart and Televerse
version: 1.0.0
repository: https://github.com/areszyn/stars

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  televerse: ^1.27.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
